### ISSUE TITLE
Não mostra o vencedor pela segunda vez, só quando reinicia o app

### ISSUE THREAD

**Issue by dotenorio** [dotenorio/pega-varetas#1]
Quando eu acabo um jogo e o vencedor é mostrado e clico em `Jogar Novamente` e finalizo o novo jogo o vencedor não é exibido.

**Comment by mdelclaro** [comment]
Olá!
Será que talvez não seja porque você não está setando a variável de volta para `false`?

```javascript
if (totalVaretasDisponiveis === totalVaretasUtilizadas && !verifedTheEnd) {
verifedTheEnd = true
```
Dessa maneira ele nunca mais vai entrar neste if. Posso tentar mandar um Pull Request e ver se isso resolve?

**Comment by dotenorio** [comment]
Será um prazer.. ❤️
